title: CS@Illinois Proficiency Exams
description: >- # this means to ignore newlines until "baseurl:"
  Information about CS@Illinois proficiency exams
url: https://proficiency.cs.illinois.edu

repository: "texne/proficiency.cs.illinois.edu"

exams:
  - 101
  - 105
  - 125
  - 173
  - 225

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_bootstrap.sh
