# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CS@Illinois Proficiency Exams
description: >- # this means to ignore newlines until "baseurl:"
  Information about CS@Illinois proficiency exams
#baseurl: "" # the subpath of your site, e.g. /blog
url: https://proficiency.cs.illinois.edu

repository: "texne/proficiency.cs.illinois.edu"

# Build settings
plugins:
  - jekyll-feed

exams:
  - 101
  - 105
  - 125
  - 173
  - 225

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
