title: CS@Illinois Proficiency Exams
description: >- # this means to ignore newlines until "baseurl:"
  Information about CS@Illinois proficiency exams
url: https://texne.github.io/proficiency.cs.illinois.edu/

repository: "texne/proficiency.cs.illinois.edu"

exams:
  - 101
  - 105
  - 125
  - 173
  - 225

include: [ 'courses' ]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_bootstrap.sh
  - courses
  - Rakefile
  - README.md
  - package-lock.json

markdown: kramdown
